export {default as Home} from "./home"
export {default as Textos} from "./textos"
export {default as Indicacoes} from "./indicacoes"
export {default as Textos2} from "./Textos2"
export {default as Register} from "./register"