export { default as Header} from "./Header"
export { default as Nav} from "./Nav"
export { default as Footer} from "./Footer"
export { default as Section} from "./Section"
export { default as Section1} from "./Section1"
export { default as Text} from "./Text"